### ISSUE TITLE
Issues upgrading to gcvor 8.4

### ISSUE THREAD

**Issue by DNKpp** [gcovr/gcovr#1164]
Hello,
I recently noticed, that version 8.4 just came out and all my coverage pipelines are now failing (because they all default to the latest version).
As it seems, gcovr runs just fine but, as I always upload all *gcov files, my upload-artifacts step failed, because no *gcov file could be found.
So, my guess is, that the `--keep` option does not work anymore?
Have a look at these two runs, where the latter uses a pinned version 8.3 and the former the 8.4.
In 8.4 run there are no *gcov files (have a look at the "Find gcov-files" steop)
https://github.com/DNKpp/mimicpp/actions/runs/18229882737/job/51910413516
https://github.com/DNKpp/mimicpp/actions/runs/18230017853/job/51910885744?pr=137

Secondly, gcovr's runtime has increased by 3-4x! Before it was at ~2min.

Lastly, I wanted to strengthen my usage of gcovr and follow the general advise to call gcovr from the actual build-directory instead of just the repo root. This was quite challenging as (to my very surprise) I had to adjust my relative filter, even though I made sure that I properly adjusted `--root` to were it pointed before. Reading the docs it states it's the *current working directory* but also mentions root. So, I think that wording should be further clarified but to be honest, this is quite unexpected that gcovr prefers the working directory over the explicit root option, because this means I should use absolute paths just to make sure the correct pattern is applied.

I also tested out the `--include` option, for which the docs says
> Files are searched recursive from the --root directory

Looking at the log, this doesn't seem to be true. This is how I call gcovr:
```
cd build
gcovr --root .. \
    --verbose \
    --include "include/mimic++(_ext)?" \
    --filter "${GITHUB_WORKSPACE}/include/mimic++(_ext)?" \
    ...
```
This is what the logs says:
> (DEBUG) File system is case sensitive.
> (DEBUG) Filters for --root: (1)
> (DEBUG)  - re.compile('^/__w/mimicpp/mimicpp/')
> (DEBUG) Filters for --filter: (1)
> (DEBUG)  - AbsoluteFilter(/__w/mimicpp/mimicpp/include/mimic++(_ext)?)
> (DEBUG) Filters for --exclude: (0)
> (DEBUG) Filters for --include: (1)
> (DEBUG)  - RelativeFilter(include/mimic++(_ext)? root=/__w/mimicpp/mimicpp/build)

As you can see, the `root=/__w/mimicpp/mimicpp/build` does not point to the directory set to `--root`, even the documentation says it should.

**Comment by Spacetown** [comment]
With 8.3 the JSON format wasn't used if call coverage was requested, this was changed with #1090. When gcov JSON format is used nothing you need to search for `*.json.gz`. 

Can you compare the runtime without verbose output? If I check the timestamps of the raw logs much of the time is spent for the logging.

> Reading the docs it states it's the current working directory but also mentions root. So, I think that wording should be further clarified but to be honest, this is quite unexpected that gcovr prefers the working directory over the explicit root option, because this means I should use absolute paths just to make sure the correct pattern is applied.

Which part of the doc are you refering to?

> As you can see, the `root=/__w/mimicpp/mimicpp/build` does not point to the directory set to `--root`, even the documentation says it should.

Your build is executed in `/__w/mimicpp/mimicpp` and you change the directory to `build`. Your `--root ..` points to `/__w/mimicpp/mimicpp` again and this is set as filter.

**Comment by DNKpp** [comment]
>Starting form GCC-14 we use now the JSON format produced by gcov instead of the textual .gcov files. The JSON format is stored as .json.gz.

Ok, this means you simply do not produce any *gcov files anymore? That's a valuable info, thanks!

> I analysed your logs and running gcov with JSON output costs about 100% additional runtime. Reading this data into the data model costs about 200-250% additional runtime.

Well, I currently need that json output to generate my coveralls ouptut in a second run, which is due to this issue: #1074 
When I fixed my pipeline for the 8.4, I'll have a look whether this is still necessary.

>You can also use a absolute path to the root or source directory here.

Sure, that's how I solved that issue. But that renders the *relative* filter a bit useless, doesn't it?


---
I gave version 8.4 another try and there seems to be a regression regarding the `-exclude-function-lines` and lambdas.
Have a look here: https://app.codecov.io/gh/DNKpp/mimicpp/pull/138/indirect-changes
All new missed lines are lambda headers.

**Comment by DNKpp** [comment]
Sure, here it is
https://github.com/DNKpp/mimicpp/actions/runs/18245862103/job/51953712103?pr=138
https://app.codecov.io/gh/DNKpp/mimicpp/pull/138/indirect-changes

Btw, the coveralls report is now pretty much unusable, regardless whether I generate it in one step or in two.

<img width="861" height="927" alt="Image" src="https://github.com/user-attachments/assets/f3afebec-9dfa-4638-b567-c0e6f8facd77" />

https://coveralls.io/builds/75826808

**Comment by DNKpp** [comment]
Why did you close the issue? My issues regarding upgrading still persist. Line count is way off, coverage percentage dropped, lambda headers are not acknowledged as function-headers, etc.

**Comment by Spacetown** [comment]
It was closed because #1165 was merged. You're jumping and referencing between two issues. Please close the issue which is fixed and reopen this with a description what's still missing.

**Comment by Spacetown** [comment]
@DNKpp Please can you check the linked PR and leave a review?

**Comment by DNKpp** [comment]
Hey @Spacetown , I made a run with the suggested commit.
Here is the relevant run https://github.com/DNKpp/mimicpp/actions/runs/19175733667/job/54819932026?pr=138
Unfortunately, I do not see much of a difference. The coverage still significantly drops by 7.7% and a lot of lambda function headers are still marked as uncovered.

<img width="691" height="752" alt="Image" src="https://github.com/user-attachments/assets/54373ff6-1e11-4c9c-bcf9-e0c2df52557d" />

see: https://app.codecov.io/gh/DNKpp/mimicpp/pull/138/indirect-changes

**Comment by DNKpp** [comment]
I may be mistaken but codecov shows more or less the same indirect changes (see my link).

<img width="1169" height="597" alt="Image" src="https://github.com/user-attachments/assets/d0389d44-8fd9-489e-9a91-3a5b1e0a3c5d" />

**Comment by DNKpp** [comment]
You can find all infos here: https://github.com/DNKpp/mimicpp/actions/runs/19175733667?pr=138

**Comment by DNKpp** [comment]
@Spacetown can you please prepare the commands you have in mind? I cannot find the `--json-trace-data-source` in the documentation.

**Comment by Spacetown** [comment]
It was introduced on main branch, see https://gcovr.com/en/latest/manpage.html#cmdoption-gcovr-json-trace-data-source.
```
gcovr --root .. \
      --keep \
      --verbose \
      --trace-include='.*Templated.*' \
      --include "${GITHUB_WORKSPACE}/include" \
      --filter "${GITHUB_WORKSPACE}/include" \
      --exclude-lines-by-pattern "\s*(MIMICPP_ASSERT|assert|util::unreachable)\(" \
      --exclude-unreachable-branches \
      --exclude-function-lines \
      --exclude-noncode-lines \
      --exclude-throw-branches \
      --decisions \
      --calls \
      --merge-lines \
      --json-trace-data-source \
      --txt \
      --json report.1.json --json-pretty \
      --cobertura cobertura.1.xml --cobertura-pretty \
      --coveralls coveralls.1.json --coveralls-pretty \
      --html-nested html/ --html-title "mimic++ Coverage Report" \
      --json-summary summary.1.json --json-summary-pretty
gcovr --root .. \
      --verbose \
      --trace-include='.*Templated.*' \
      --include "${GITHUB_WORKSPACE}/include" \
      --filter "${GITHUB_WORKSPACE}/include" \
      --exclude-lines-by-pattern "\s*(MIMICPP_ASSERT|assert|util::unreachable)\(" \
      --exclude-unreachable-branches \
      --exclude-function-lines \
      --exclude-noncode-lines \
      --exclude-throw-branches \
      --decisions \
      --calls \
      --merge-lines \
      --json-trace-data-source \
      --add-tracefile report.1.json \
      --txt \
      --json report.2.json --json-pretty \
      --cobertura cobertura.2.xml --cobertura-pretty \
      --coveralls coveralls.2.json --coveralls-pretty \
      --json-summary summary.2.json --json-summary-pretty
```

There should be many TRACE messages for Templated.hpp. If not, you need to adapt the `--trace-include='.*Templated.*'`.

In the JSON from the last file there were counters with a value of 0 and with the `--json-trace-data-source` we will see from where this was coming:
```json
                {
                    "line_number": 161,
                    "function_name": "_ZNK7mimicpp8printing4type6detail46potential_pmr_container_type_name_generator_fnIN12_GLOBAL__N_113custom_vectorENS_4util9type_listIJiNSt3pmr21polymorphic_allocatorIiEEEEEEclISt19ostreambuf_iteratorIcSt11char_traitsIcEEEET_SI_",
                    "block_ids": [
                        26
                    ],
                    "count": 0,
                    "branches": [],
                    "gcovr/md5": "9cf90df9e5e4999d1374cf97a8482f2c"
                },
```

**Comment by DNKpp** [comment]
Hi @Spacetown , thanks for the explanation.
[Here](https://github.com/DNKpp/mimicpp/actions/runs/19395186694?pr=138) you can find all artifacts.
As with the previous run, here are the [coveralls](https://coveralls.io/builds/76496966) and [codecov](https://app.codecov.io/gh/DNKpp/mimicpp/pull/138/indirect-changes) infos.

**Comment by Spacetown** [comment]
@DNKpp Here is the source of the data:
```json
        {
          "line_number": 161,
          "function_name": "_ZNK7mimicpp8printing4type6detail46potential_pmr_container_type_name_generator_fnISt12forward_listNS_4util9type_listIJS4_IiNSt3pmr21polymorphic_allocatorIiEEENS8_ISA_EEEEEEclISt19ostreambuf_iteratorIcSt11char_traitsIcEEEET_SJ_",
          "count": 0,
          "unexecuted_block": false,
          "block_ids": [
            26
          ],
          "branches": [],
          "calls": [],
          "conditions": []
        },
```

In 8.3 a line had only one set off coverage information and if we found a function definition at this line the whole data was excluded. With commit [41b9fa3d19d948a9ad450615c0cf63d27f668c13](https://github.com/gcovr/gcovr/pull/1137/commits/41b9fa3d19d948a9ad450615c0cf63d27f668c13) of #1137 the line is not merged anymore and we only remove the data which belongs to the function defined there.

From https://gcovr.com/en/stable/known_bugs.html#discrepancy-between-exclusion-and-removal-of-coverage-data:
- The coverage of a whole line was removed if a function started on this line, even if the line
  coverage belongs to another function. Now only the data for this function is removed.

What I'm wondering here is a count of 0 but no unexecuted blocks.

**Comment by Spacetown** [comment]
@DNKpp Please can you check the linked PR? This should solve the last issue.

**Comment by DNKpp** [comment]
Hi, I did it.
But now, there are other lambda headers reported as unconvered.
https://app.codecov.io/gh/DNKpp/mimicpp/pull/138/indirect-changes

[Here](https://github.com/DNKpp/mimicpp/actions/runs/19786733300?pr=138) is the run.
